default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  adapter: postgresql
  encoding: unicode
  database: lab_portal_development
  username: postgres
  password: Mariasql!@#0208
  host: localhost


test:
  <<: *default
  database: lab_portal_test
  host: localhost
  username: postgres
  password: "Mariasql!@#0208"
