default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: lab_portal_development
  host: localhost
  username: postgres
  password: "123456789"

test:
  <<: *default
  database: lab_portal_test
  host: localhost
  username: postgres
  password: "123456789"
